import random

thoughts_for_the_day = [
    "A broad mind lacks focus.",
    "A coward always seeks compromise.",
    "A coward's only reward is to live in fear another day.",
    "A dedicated life may reach the end of infinity.",
    "A fine mind is a blessing of the Emperor - it should not be cluttered with trivialities.",
    "A logical argument must be dismissed with absolute conviction!",
    "A mind without purpose will wander in dark places.",
    "A moment of laxity spawns a lifetime of heresy.",
    "A questioning mind betrays a treacherous soul.",
    "A questioning servant is more dangerous than an ignorant heretic.",
    "A single thought of heresy can blight a lifetime of faithful duty.",
    "A small mind is a tidy mind.",
    "A small mind is easily filled with faith.",
    "A suspicious mind is a healthy mind.",
    "A warrior's faith in his commander is his best armour and his strongest weapon.",
    "A weapon cannot substitute for zeal.",
    "A wise man learns from the death of others.",
    "Abhor the night, it is the Light that endures.",
    "Accept your lot!",
    "Against the alien and the traitor there is no fair way to fight.",
    "All Daemons are Falsehood. They are lies given the shape of creatures by the fell power of Chaos.",
    "All hail the martyrs! On their blood is our Imperium founded, in their remembrance do we honour ourselves.",
    "All mortal life is folly that does not feed the spirit.",
    "All our ignorances bring us closer to annihilation.",
    "All praise to the Emperor.",
    "All souls cry out for salvation.",
    "An alien mind cannot accept the Emperor's blessing.",
    "An empty mind is a loyal mind.",
    "An open mind is like a fortress with its gate unbarred and unguarded.",
    "An unprotected soul can no more cross the storms of the warp than a heretic can bear the gaze of the Inquisition.",
    "Analysis is the bane of conviction.",
    "Appeasement is a curse.",
    "As the mind to the body so the soul to the spirit, as death to the mortal man so failure to the immortal, such is the price of all ambition.",
    "Be courageous and bold, be humble before your masters, lead with valour! These things above all others will be of use when your time comes to die.",
    "Be grateful of your master's favour!",
    "Be pure.",
    "Be strong in your ignorance.",
    "Be vigilant and strong. The Emperor knows what evil lurks in the vacillation of a weak fool.",
    "Better crippled in body than corrupt in mind.",
    "Better to self-destruct than acquiesce.",
    "Big guns never tire.",
    "Blessed are the gun makers.",
    "Blessed is the mind too small for doubt",
    "Blind faith is a just cause.",
    "Brave are they who know everything yet fear nothing.",
    "Burn the Heretic! Kill the Mutant! Purge the Unclean!",
    "Burn the unclean with the fires of purity.",
    "By the manner of our death are we judged.",
    "By the manner of their death we shall know them.",
    "Call no man happy until he is dead.",
    "Carry the Emperor's will as your torch, with it destroy the shadows.",
    "Cast out the mutant, the traitor, the heretic. For every enemy without there are a hundred within.",
    "Cease and repent!",
    "Cease purpose and die.",
    "Cleanse yourself in the blood of our enemies.",
    "Compromise is akin to treachery.",
    "Contemplation is the womb of treachery.",
    "Courage is the Emperor's gift: repay him with victory.",
    "Courage is the mastery of fear - not the absence of fear.",
    "Curse now the death in vain.",
    "Damnation is eternal.",
    "Dark dreams lie upon the heart.",
    "Death brings its own reward.",
    "Death is honour.",
    "Death is the only answer",
    "Death is the servant of the righteous.",
    "Defile not His presence.",
    "Defile the mutant.",
    "Do not question the will of the Emperor!",
    "Do not wait for death.",
    "Doubt forms the path to damnation.",
    "Doubt is a sign of weakness.",
    "Drink deep of victory and remember the fallen.",
    "Duty prevails.",
    "Enlightenment is a myth we do not need to understand in order to hate.",
    "Even a man who has nothing can still offer his life.",
    "Every lone spirit doubts his strength",
    "Examine your thoughts!",
    "Excuses are the refuge of the weak.",
    "Exist for the Emperor.",
    "Faith grows from the barrel of a gun.",
    "Faith, hate and ignorance.",
    "Faith. Honour. Vigilance.",
    "Faith in the Emperor is its own reward.",
    "Faith is stronger than adamantium.",
    "Faith is the strongest shield.",
    "Faith is your shield.",
    "Faith without deeds is worthless.",
    "Fear not death, for the soul of the faithful man never dies.",
    "Fear not the creatures of the jungle but those that lurk within your mind.",
    "Fear the shadows; despise the night. There are horrors that no man can face and survive.",
    "Follow the Emperor, and the glory of victory shall be yours.",
    "Foolish are those who fear nothing, yet claim to know everything.",
    "For a warrior the only crime is cowardice.",
    "For every battle honour, a thousand heroes die alone, unsung, and unremembered.",
    "For the foes of Mankind, the only mercy is a swift death.",
    "For those who seek perfection there can be no rest this side of the grave.",
    "Forgiveness is a sign of weakness.",
    "Forward brothers, with loyalty to victory and glory!",
    "Glory in death is life Eternal.",
    "Happiness is a delusion of the weak.",
    "Hard work conquers everything.",
    "Hate enriches.",
    "Hatred is our surest weapon.",
    "Hatred is the Emperor's greatest gift to humanity.",
    "Hatred steels our resolve.",
    "He bears the weight of Mankind's ills.",
    "He who allows the alien to live shares its crime of existence.",
    "He who lives for nothing is nothing. He who dies for the Emperor is a hero.",
    "He who picks up the sword against us, shall perish by it.",
    "Heresy grows from idleness.",
    "Heresy must be met with hatred.",
    "His will be done.",
    "His word is our strength.",
    "Honour is what a pure mind knows about itself.",
    "Honour your Chapter.",
    "Honour, duty and obedience.",
    "Hope is the beginning of unhappiness.",
    "Hope is the first step on the road to disappointment.",
    "Humanity is an ocean; if a few drops of the ocean are polluted then the ocean is tainted."
]

def get_thought_for_the_day():
    return random.choice(thoughts_for_the_day)
